name: GitHub Pages - Build and Deploy

on:
  push:
    branches: [main] # Or your default branch
    paths-ignore:
      - 'output/**'       # Ignore changes in the output folder

  workflow_dispatch: # Optional: Allows manual triggering

permissions:
  id-token: write 
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby and Jekyll
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x' # Or the Ruby version your Jekyll site uses
          cache: bundler # Corrected syntax for bundler cache

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages