name: GitHub Pages - Build and Deploy

on:
  push:
    branches: [main] # Or your default branch
    paths-ignore:
      - 'output/**'       # Ignore changes in the output folder

  workflow_dispatch: # Optional: Allows manual triggering

permissions:
  id-token: write 
  contents: read
  pages: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.8'
       
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false
          build_revision: ${{ github.sha }}
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for symlinks
        run: |
          echo "Checking for symlinks in _site directory"
          find _site -type l || echo "No symlinks found"

      - name: Remove problematic files
        run: |
          # Remove potential problematic files
          rm -rf _site/output || true
          rm -f _site/rss_reformatter.py || true
          find _site -type l -delete || true
          
      - name: List _site contents
        run: ls -al _site
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site
          retention-days: 1
          if-no-files-found: error

  # Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site
          
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4