name: Update RSS Feeds & Deploy Site

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours

  workflow_dispatch:       # Manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    # PART 1: Update RSS Feeds
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser PyRSS2Gen
        
    - name: Run RSS reformatter
      run: |
        mkdir -p output
        python3 rss_reformatter.py --feed-file feeds.txt
        
    - name: Commit RSS feed changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add output/
        git commit -m "Update RSS feeds - $(date)" || echo "No changes to commit"
        git push
