name: RSS Feed Update and Deploy

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  reformat-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser PyRSS2Gen
        
    - name: Run RSS reformatter
      run: |
        mkdir -p output
        python3 rss_reformatter.py --feed-file feeds.txt
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add output/
        git commit -m "Update RSS feeds - $(date)" || echo "No changes to commit"
        git push

  deploy-to-pages:
    needs: reformat-rss
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      # Create a temporary directory to hold the complete site structure
      - name: Prepare site directory
        run: |
          # Create a temporary directory for the whole site
          mkdir -p _site
          
          # Copy all website files to _site (excluding .git, .github, etc.)
          rsync -av --exclude='.git' --exclude='.github' --exclude='_site' ./ _site/
          
          # Make sure output directory exists in _site
          mkdir -p _site/output
          
          # Copy latest RSS files (they should be fresher in the repo after the previous job)
          cp -r output/* _site/output/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      # Upload the ENTIRE site, not just output directory
      - name: Upload entire site
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          retention-days: 1
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4