name: RSS Feed Update and Deploy

# Set when the workflow will run
on:
  schedule:
    # WINTER TIME - 0 5-17/4 * * * # Every 4 hours between 5 AM and 5 PM UTC
    # SUMMER TIME - 0 4-16/4 * * * # Every 4 hours between 4 AM and 4 PM UTC
    - cron: '0 */4 * * *'  # Every 4 hours between 4 AM and 4 PM UTC
  # Optional: Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  reformat-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser PyRSS2Gen
        
    - name: Run RSS reformatter
      run: |
        # Create output directory
        mkdir -p output
        
        # Add your feeds here - examples for different sites
        python3 rss_reformatter.py --feed-file feeds.txt
        # Add more feeds as needed
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add output/
        git commit -m "Update RSS feeds - $(date)" || echo "No changes to commit"
        git push

  deploy-to-pages:
    needs: reformat-rss
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Ensure we get the latest commits including those from the previous job
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload RSS files only
        uses: actions/upload-pages-artifact@v3
        with:
          path: output
          retention-days: 1  # Minimum retention
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4