name: Test Cron Job

on:
  schedule:
    # This runs every minute
    # Adjust the cron expression as needed
    # - cron: '0 6-22/2 * * *'
    - cron: '* * * * *'
  # Optional: Allow manual triggering   
  workflow_dispatch:
permissions:
  contents: write
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date